# Site settings
title: Under Construction
tag_text: Under Construction 
description: This site is under construction. 

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
